# "seconds": "Y",
#  "fiveHourRow": "RROO",
#  "oneHourRow": "RROO",
#  "fiveMinuteRow": "OOOOOOOOOOO",
#  "oneMinuteRow": "YYOO"
# Y, R, O representing the color of it, Yellow, Red, Off for lights of the Berlin clock

### GET For retrieving string presentation of the time for berlinClock
GET {{baseUrl}}/berlinClock
